# Generated by Django 4.2.8 on 2023-12-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('long_url', models.URLField()),
                ('short_url', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
